import { Button } from "@/components/ui/button";
import { ArrowLeft, TrendingDown, Download, Camera, TrendingUp, Activity, Droplets, Calendar } from "lucide-react";
import { Link } from "react-router-dom";
import BottomNav from "@/components/BottomNav";
import { PageTransition } from "@/components/animations/PageTransition";
import { motion } from "framer-motion";
import { useUserProfile } from "@/hooks/useUserProfile";
import { useWeightUnit } from "@/contexts/WeightUnitContext";
import { useMeals } from "@/hooks/useFirestore";
import { LoadingSkeleton } from "@/components/LoadingSkeleton";
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { useState, useMemo } from "react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { WeightChart } from "@/components/charts/WeightChart";
import { ActivityChart } from "@/components/charts/ActivityChart";
import { useWeightData } from "@/hooks/useWeightData";
import { useActivityData } from "@/hooks/useActivityData";

const Progress = () => {
  const { profile, loading: profileLoading } = useUserProfile();
  const [today] = useState(() => new Date());
  const { meals, loading: mealsLoading } = useMeals(today);
  const { formatWeight } = useWeightUnit();
  const { toast } = useToast();
  const [selectedTimeframe, setSelectedTimeframe] = useState('3M');
  const timeframes = ['1M', '3M', '6M', '1Y'];
  
  // Fetch chart data
  const { weightData, loading: weightLoading, goalWeight } = useWeightData(selectedTimeframe);
  const { activityData, loading: activityLoading, summaryStats } = useActivityData(selectedTimeframe);
  
  // Calculate actual stats from meals data
  const todayCalories = useMemo(() => {
    return meals.reduce((total, meal) => total + (meal.calories || 0), 0);
  }, [meals]);

  const todayMeals = meals.length;

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(102, 126, 234); // Primary color
    doc.text('Intentional - Progress Report', 14, 20);
    
    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 28);
    
    // User Info
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Progress Summary for ${profile?.displayName || 'User'}`, 14, 40);
    
    // Stats Table
    const statsData = [
      ['Current Streak', `${profile?.currentStreak || 0} days`],
      ['Longest Streak', `${profile?.longestStreak || 0} days`],
      ['Total Entries', `${profile?.totalEntries || 0}`],
      ['Total Meals Logged', `${profile?.totalMeals || 0}`],
      ['Total Water Glasses', `${profile?.totalWaterGlasses || 0}`],
    ];

    if (profile?.startingWeight && profile?.currentWeight) {
      statsData.push(
        ['Starting Weight', formatWeight(profile.startingWeight)],
        ['Current Weight', formatWeight(profile.currentWeight)],
        ['Weight Lost', formatWeight(profile.startingWeight - profile.currentWeight)]
      );
    }

    if (profile?.goalWeight) {
      statsData.push(
        ['Goal Weight', formatWeight(profile.goalWeight)],
        ['Remaining', formatWeight(Math.max(0, (profile.currentWeight || 0) - profile.goalWeight))]
      );
    }

    autoTable(doc, {
      head: [['Metric', 'Value']],
      body: statsData,
      startY: 48,
      theme: 'grid',
      headStyles: { fillColor: [102, 126, 234], textColor: 255 },
      margin: { left: 14 },
    });

    // Recent Meals
    if (meals.length > 0) {
      const finalY = (doc as any).lastAutoTable.finalY + 10;
      doc.setFontSize(14);
      doc.text('Recent Meals', 14, finalY);
      
      const mealData = meals.slice(0, 10).map(meal => [
        new Date(meal.createdAt as any).toLocaleDateString(),
        meal.type || 'N/A',
        meal.calories ? `${meal.calories} cal` : 'Not tracked',
        meal.notes?.substring(0, 40) || '-'
      ]);

      autoTable(doc, {
        head: [['Date', 'Type', 'Calories', 'Notes']],
        body: mealData,
        startY: finalY + 5,
        theme: 'striped',
        headStyles: { fillColor: [102, 126, 234] },
        margin: { left: 14 },
      });
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
      doc.text(
        'Generated by Intentional - Your Wellness Journey',
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 6,
        { align: 'center' }
      );
    }

    // Save
    doc.save(`progress-report-${new Date().toLocaleDateString()}.pdf`);
    
    toast({
      title: "PDF Downloaded!",
      description: "Your progress report has been saved",
    });
  };
  
  const isLoading = profileLoading || mealsLoading || weightLoading || activityLoading;

  return (
    <PageTransition>
      <div className="min-h-screen bg-background pb-32 relative overflow-hidden">
        {/* Background Gradients */}
        <div className="fixed top-0 left-0 w-full h-full overflow-hidden -z-10 pointer-events-none">
          <div className="absolute top-[-10%] right-[-10%] w-[500px] h-[500px] rounded-full bg-primary/5 blur-[100px]" />
          <div className="absolute bottom-[-10%] left-[-10%] w-[500px] h-[500px] rounded-full bg-secondary/5 blur-[100px]" />
        </div>

        {isLoading ? (
          <>
            <LoadingSkeleton />
            <BottomNav />
          </>
        ) : (
          <>
            {/* Header */}
            <div className="px-6 pt-8 pb-6">
              <div className="flex items-center justify-between mb-6">
                <Link to="/">
                  <Button variant="ghost" size="icon">
                    <ArrowLeft className="w-5 h-5" />
                  </Button>
                </Link>
                <Button
                  onClick={handleExportPDF}
                  variant="outline"
                  size="sm"
                  className="rounded-full h-9 px-4 bg-background/50 backdrop-blur-sm border-primary/20 hover:bg-primary/5"
                >
                  <Download className="w-4 h-4 mr-2 text-primary" />
                  Export PDF
                </Button>
              </div>

              <div className="flex items-center gap-3 mb-6">
                <div className="w-12 h-12 bg-gradient-to-br from-primary to-accent rounded-2xl flex items-center justify-center shadow-glow">
                  <TrendingUp className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h1 className="text-3xl font-bold font-heading">Your Progress</h1>
                  <p className="text-muted-foreground text-sm">Track your journey</p>
                </div>
              </div>

              {/* Timeframe Selector */}
              <div className="flex p-1 bg-secondary/50 rounded-2xl backdrop-blur-sm border border-border/50">
                {timeframes.map((tf) => (
                  <button
                    key={tf}
                    onClick={() => setSelectedTimeframe(tf)}
                    className={`flex-1 py-2 text-sm font-medium rounded-xl transition-all duration-300 ${
                      selectedTimeframe === tf
                        ? "bg-background text-primary shadow-sm"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {tf}
                  </button>
                ))}
              </div>
            </div>

            <div className="px-6 space-y-6">
              {/* Achievement Card */}
              {profile && profile.currentStreak > 0 && (
                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-gradient-to-br from-primary to-accent rounded-3xl p-6 shadow-glow text-white relative overflow-hidden"
                >
                  <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-2xl -mr-10 -mt-10" />
                  <div className="relative z-10">
                    <p className="text-white/80 text-sm mb-2 font-medium flex items-center gap-2">
                      <span className="text-lg">🏆</span> Current Streak
                    </p>
                    <p className="text-white text-lg leading-relaxed font-medium">
                      {profile.startingWeight && profile.currentWeight ? (
                        <>
                          Awesome job! You've lost <span className="font-bold bg-white/20 px-2 py-0.5 rounded-lg">{formatWeight(profile.startingWeight - profile.currentWeight)}</span> and you're on a <span className="font-bold bg-white/20 px-2 py-0.5 rounded-lg">{profile.currentStreak}-day check-in streak</span>. Keep it up!
                        </>
                      ) : (
                        <>
                          Great progress! You're on a <span className="font-bold bg-white/20 px-2 py-0.5 rounded-lg">{profile.currentStreak}-day streak</span>. Keep it up!
                        </>
                      )}
                    </p>
                  </div>
                </motion.div>
              )}

              {/* Weight Journey */}
              {profile && (profile.startingWeight || profile.goalWeight) ? (
                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                  className="bg-card/50 backdrop-blur-sm rounded-3xl p-6 shadow-sm border border-border/50"
                >
                  <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-blue-500/10 rounded-xl flex items-center justify-center">
                        <TrendingDown className="w-5 h-5 text-blue-500" />
                      </div>
                      <h2 className="text-lg font-semibold font-heading">Weight Journey</h2>
                    </div>
                    <Link to="/progress-photos">
                      <Button variant="ghost" size="sm" className="text-primary hover:bg-primary/10 rounded-xl">
                        <Camera className="w-4 h-4 mr-2" />
                        Photos
                      </Button>
                    </Link>
                  </div>
                  
                  <div className="flex justify-between text-sm text-muted-foreground mb-6 bg-secondary/30 p-4 rounded-2xl">
                    {profile.startingWeight && (
                      <div className="text-center">
                        <p className="text-xs mb-1">Starting</p>
                        <p className="font-bold text-foreground text-lg">{formatWeight(profile.startingWeight)}</p>
                      </div>
                    )}
                    <div className="w-px bg-border/50" />
                    {profile.currentWeight && (
                      <div className="text-center">
                        <p className="text-xs mb-1">Current</p>
                        <p className="font-bold text-primary text-lg">{formatWeight(profile.currentWeight)}</p>
                      </div>
                    )}
                    <div className="w-px bg-border/50" />
                    {profile.goalWeight && (
                      <div className="text-center">
                        <p className="text-xs mb-1">Goal</p>
                        <p className="font-bold text-foreground text-lg">{formatWeight(profile.goalWeight)}</p>
                      </div>
                    )}
                  </div>
                  
                  {/* Weight Chart */}
                  <WeightChart 
                    data={weightData}
                    goalWeight={goalWeight}
                    timeframe={selectedTimeframe}
                    className=""
                  />
                </motion.div>
              ) : (
                <div className="bg-card/50 backdrop-blur-sm rounded-3xl p-8 shadow-sm border border-border/50 text-center">
                  <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                    <TrendingDown className="w-8 h-8 text-primary" />
                  </div>
                  <h2 className="text-xl font-semibold mb-2 font-heading">Start Your Journey</h2>
                  <p className="text-muted-foreground mb-6 text-sm">Set your weight goals to track your progress and see your achievements.</p>
                  <Link to="/profile">
                    <Button className="bg-primary hover:bg-primary/90 text-primary-foreground rounded-2xl shadow-glow px-8">
                      Set Goals
                    </Button>
                  </Link>
                </div>
              )}

              {/* Activity Trends Chart */}
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="bg-card/50 backdrop-blur-sm rounded-3xl p-6 shadow-sm border border-border/50"
              >
                <div className="flex items-center justify-between mb-6">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-orange-500/10 rounded-xl flex items-center justify-center">
                      <Activity className="w-5 h-5 text-orange-500" />
                    </div>
                    <h2 className="text-lg font-semibold font-heading">Activity Trends</h2>
                  </div>
                  {summaryStats.streak > 0 && (
                    <div className="text-right">
                      <p className="text-xs text-muted-foreground">Current Streak</p>
                      <p className="text-sm font-semibold text-orange-600">
                        {summaryStats.streak} {summaryStats.streak === 1 ? 'day' : 'days'}
                      </p>
                    </div>
                  )}
                </div>
                <ActivityChart 
                  data={activityData}
                  timeframe={selectedTimeframe}
                  className=""
                />
              </motion.div>

              {/* Health Stats */}
              {profile && (
                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.3 }}
                >
                  <h2 className="text-lg font-semibold mb-4 font-heading px-1">Your Stats</h2>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-card/50 backdrop-blur-sm rounded-3xl p-5 shadow-sm border border-border/50">
                      <div className="w-8 h-8 bg-primary/10 rounded-lg flex items-center justify-center mb-3">
                        <Calendar className="w-4 h-4 text-primary" />
                      </div>
                      <p className="text-xs text-muted-foreground mb-1">Active Days</p>
                      <p className="text-2xl font-bold font-heading">{summaryStats.activeDays}</p>
                    </div>
                    <div className="bg-card/50 backdrop-blur-sm rounded-3xl p-5 shadow-sm border border-border/50">
                      <div className="w-8 h-8 bg-orange-500/10 rounded-lg flex items-center justify-center mb-3">
                        <Activity className="w-4 h-4 text-orange-500" />
                      </div>
                      <p className="text-xs text-muted-foreground mb-1">Total Meals</p>
                      <p className="text-2xl font-bold font-heading">{summaryStats.totalMeals}</p>
                    </div>
                    <div className="bg-card/50 backdrop-blur-sm rounded-3xl p-5 shadow-sm border border-border/50">
                      <div className="w-8 h-8 bg-cyan-500/10 rounded-lg flex items-center justify-center mb-3">
                        <Droplets className="w-4 h-4 text-cyan-500" />
                      </div>
                      <p className="text-xs text-muted-foreground mb-1">Water Glasses</p>
                      <p className="text-2xl font-bold font-heading">{summaryStats.totalWaterGlasses}</p>
                    </div>
                    <div className="bg-card/50 backdrop-blur-sm rounded-3xl p-5 shadow-sm border border-border/50">
                      <div className="w-8 h-8 bg-green-500/10 rounded-lg flex items-center justify-center mb-3">
                        <TrendingUp className="w-4 h-4 text-green-500" />
                      </div>
                      <p className="text-xs text-muted-foreground mb-1">Avg Performance</p>
                      <p className="text-2xl font-bold font-heading">{Math.round(summaryStats.averageCompletionRate)}<span className="text-sm font-normal text-muted-foreground">%</span></p>
                    </div>
                  </div>
                </motion.div>
              )}

              {/* Recent Meals */}
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
              >
                <div className="flex justify-between items-center mb-4 px-1">
                  <h2 className="text-lg font-semibold font-heading">Recent Meals</h2>
                  <Link to="/meal-history">
                    <Button variant="ghost" size="sm" className="text-primary hover:bg-primary/10 rounded-xl h-8 text-xs">View All</Button>
                  </Link>
                </div>
                
                {meals.length > 0 ? (
                  <div className="grid grid-cols-3 gap-3">
                    {meals.slice(0, 3).map((meal) => (
                      <div
                        key={meal.id}
                        className="aspect-square rounded-3xl bg-secondary/50 border border-border/50 overflow-hidden relative group"
                      >
                        {meal.imageUrl ? (
                          <img src={meal.imageUrl} alt="Meal" className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" />
                        ) : (
                          <div className="w-full h-full bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center">
                            <span className="text-2xl">🍽️</span>
                          </div>
                        )}
                        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-3">
                          <p className="text-white text-xs font-medium truncate w-full">{meal.calories} kcal</p>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="bg-card/50 backdrop-blur-sm rounded-3xl p-8 shadow-sm border border-border/50 text-center">
                    <p className="text-muted-foreground mb-4 text-sm">No meals logged yet</p>
                    <Link to="/log-meal">
                      <Button className="bg-primary hover:bg-primary/90 text-primary-foreground rounded-2xl shadow-glow">
                        Log Your First Meal
                      </Button>
                    </Link>
                  </div>
                )}
              </motion.div>
            </div>

            {/* Bottom Navigation */}
            <BottomNav />
          </>
        )}
      </div>
    </PageTransition>
  );
};

export default Progress;
